### ISSUE TITLE
user authorization levels

### ISSUE THREAD

**Issue by easmith2** [Rails-Dream-Team/TIY-Final-Project#124]
This issue is for tracking progress on the implementation of tiered user authorization. 
Desired functionality should be added with an empty checkbox. When the functionality has been implemented and tested, it should be checked off. 

### Home

_Index_
- [x] Basic
- [x] Volunteer
- [x] Admin

---

### Colonies

_Index_
 - [x] Volunteer
 - [x] Admin

_Show_
 - [x] Volunteer
 - [x] Admin

_Edit_
- [x] Admin

_Create_
- [x] Admin

_Delete_
- [x] Admin

---

### Organizations

_Index_
 - [x] Basic
 - [x] Volunteer
 - [x] Admin

_Show_
 - [x] Basic
 - [x] Volunteer
 - [x] Admin

_Create_
- [x] Basic
- [x] Volunteer
- [x] Admin

_Edit_
- [x] Volunteer
- [x] Admin

_Delete_
- [x] Admin

---

### Volunteer Form

_View + Submit_
- [ ] Basic
- [ ] Volunteer
- [ ] Admin

---

### Report Colony Form

_View + Submit_
- [ ] Basic
- [ ] Volunteer
- [ ] Admin

---

### Boards

_View Boards_
 - [x] Unauthenticated **Lost & Found only**
 - [x] Basic
 - [x] Volunteer
 - [x] Admin

_Create Board_
 - [x] Admin

_Edit a Board_
 - [x] Admin

_Delete a Board_
 - [x] Admin

---

### Topics

_View Topics_
 - [x] Unauthenticated **scoped to Lost & Found only**
 - [x] Basic
 - [x] Volunteer
 - [x] Admin

_Create Topic_
 - [x] Unauthenticated **under Lost & Found only**
 - [x] Basic
 - [x] Volunteer
 - [x] Admin

_Edit a Topic (scoped to those created by the user)_
 - [x] Basic
 - [x] Volunteer
 - [x] Admin

_Delete a Topic_
 - [x] Admin

---

### Post

_View Posts_
_not needed, these are only shown under a topic_

_Create Post_
 - [x] Unauthenticated **Lost & Found Only**
 - [x] Basic
 - [x] Volunteer
 - [x] Admin

_Edit a Post (scoped to those created by the user)_
 - [x] Basic
 - [x] Volunteer
 - [x] Admin

_Delete a Post_
 - [x] Admin

**Comment by jasimper** [comment]
Volunteer and Report Colony Forms were not given pundit policies as they are fully available to anyone who logs in.
